// This file is generated by flutter_rust_bridge
// Dart FFI bindings for the Rust MPC core
//
// IMPORTANT: This is a manually-created binding file since flutter_rust_bridge_codegen
// is not available in the current environment. In a real setup, run:
// flutter_rust_bridge_codegen generate

import 'dart:async';
import 'dart:typed_data';

// ---------------------------------------------------------------------------
// FFI Data Structures (matching Rust structs)
// ---------------------------------------------------------------------------

class FfiWalletInfo {
  final String address;
  final Uint8List publicKey;

  FfiWalletInfo({
    required this.address,
    required this.publicKey,
  });
}

class FfiBalance {
  final String wei;
  final String formatted;
  final int decimals;

  FfiBalance({
    required this.wei,
    required this.formatted,
    required this.decimals,
  });
}

class FfiTxResult {
  final String txHash;

  FfiTxResult({required this.txHash});
}

class FfiGasEstimate {
  final int gasLimit;
  final String maxFeePerGas;
  final String maxPriorityFeePerGas;
  final String estimatedCostWei;

  FfiGasEstimate({
    required this.gasLimit,
    required this.maxFeePerGas,
    required this.maxPriorityFeePerGas,
    required this.estimatedCostWei,
  });
}

class FfiKeyStatus {
  final bool hasDeviceShard;
  final bool hasServerShard;
  final bool hasBackupShard;
  final String address;

  FfiKeyStatus({
    required this.hasDeviceShard,
    required this.hasServerShard,
    required this.hasBackupShard,
    required this.address,
  });
}

class FfiDkgSession {
  final String sessionId;

  FfiDkgSession({required this.sessionId});
}

class FfiRound1Result {
  final String messageJson;

  FfiRound1Result({required this.messageJson});
}

class FfiRound2Result {
  final String messageJson;

  FfiRound2Result({required this.messageJson});
}

class FfiDkgComplete {
  final String address;
  final Uint8List publicKey;

  FfiDkgComplete({
    required this.address,
    required this.publicKey,
  });
}

class FfiSignRound1 {
  final Uint8List payload;
  final Uint8List msgHash;
  final String sessionId;

  FfiSignRound1({
    required this.payload,
    required this.msgHash,
    required this.sessionId,
  });
}

class FfiSignResult {
  final Uint8List signature;

  FfiSignResult({required this.signature});
}

class FfiReshareSession {
  final String sessionId;

  FfiReshareSession({required this.sessionId});
}

class FfiReshareRound1Result {
  final List<String> messagesJson;

  FfiReshareRound1Result({required this.messagesJson});
}

class FfiReshareComplete {
  final String address;
  final Uint8List publicKey;

  FfiReshareComplete({
    required this.address,
    required this.publicKey,
  });
}

class FfiPresignRound1 {
  final String sessionId;
  final Uint8List payload;

  FfiPresignRound1({
    required this.sessionId,
    required this.payload,
  });
}

class FfiPresignComplete {
  final Uint8List presigData;

  FfiPresignComplete({required this.presigData});
}

// ---------------------------------------------------------------------------
// API Class (singleton interface to Rust FFI)
// ---------------------------------------------------------------------------

class Api {
  // In a real flutter_rust_bridge setup, this would load the native library
  // For now, this is a placeholder that throws unimplemented errors

  static Api? _instance;

  Api._internal();

  factory Api() {
    _instance ??= Api._internal();
    return _instance!;
  }

  // ---------------------------------------------------------------------------
  // Wallet Operations
  // ---------------------------------------------------------------------------

  /// Generate a new MPC wallet using local-mode TSS (2-of-3).
  /// Returns the derived Ethereum address and public key.
  Future<FfiWalletInfo> generateWallet() async {
    return _callNative<FfiWalletInfo>(
      'generate_wallet',
      [],
      (result) => FfiWalletInfo(
        address: result['address'] as String,
        publicKey: Uint8List.fromList(List<int>.from(result['public_key'])),
      ),
    );
  }

  /// Check if wallet shares are loaded in memory.
  Future<bool> hasWallet() async {
    return _callNative<bool>(
      'has_wallet',
      [],
      (result) => result as bool,
    );
  }

  /// Get the key status for the UI (which shards are present).
  Future<FfiKeyStatus> getKeyStatus() async {
    return _callNative<FfiKeyStatus>(
      'get_key_status',
      [],
      (result) => FfiKeyStatus(
        hasDeviceShard: result['has_device_shard'] as bool,
        hasServerShard: result['has_server_shard'] as bool,
        hasBackupShard: result['has_backup_shard'] as bool,
        address: result['address'] as String,
      ),
    );
  }

  /// Clear all shares from memory (for wallet deletion / reset).
  Future<void> clearWallet() async {
    await _callNative<void>(
      'clear_wallet',
      [],
      (_) {},
    );
  }

  // ---------------------------------------------------------------------------
  // DKG Protocol — Distributed Key Generation (3-round protocol)
  // ---------------------------------------------------------------------------

  /// Initialize a new DKG session.
  Future<FfiDkgSession> dkgSessionNew(int partyIndex) async {
    return _callNative<FfiDkgSession>(
      'dkg_session_new',
      [partyIndex],
      (result) => FfiDkgSession(
        sessionId: result['session_id'] as String,
      ),
    );
  }

  /// DKG Round 1: Generate commitments to VSS polynomial.
  Future<FfiRound1Result> dkgGenerateRound1(String sessionId) async {
    return _callNative<FfiRound1Result>(
      'dkg_generate_round1',
      [sessionId],
      (result) => FfiRound1Result(
        messageJson: result['message_json'] as String,
      ),
    );
  }

  /// DKG Round 1: Process all commitments from other parties.
  Future<void> dkgProcessRound1(String sessionId, List<String> messagesJson) async {
    await _callNative<void>(
      'dkg_process_round1',
      [sessionId, messagesJson],
      (_) {},
    );
  }

  /// DKG Round 2: Generate secret share evaluations.
  Future<List<String>> dkgGenerateRound2(String sessionId) async {
    return _callNative<List<String>>(
      'dkg_generate_round2',
      [sessionId],
      (result) => List<String>.from(result as List),
    );
  }

  /// DKG Round 2: Process share evaluations from other parties.
  Future<void> dkgProcessRound2(String sessionId, List<String> messagesJson) async {
    await _callNative<void>(
      'dkg_process_round2',
      [sessionId, messagesJson],
      (_) {},
    );
  }

  /// Finalize DKG and extract the key share.
  Future<FfiDkgComplete> dkgFinalize(String sessionId) async {
    return _callNative<FfiDkgComplete>(
      'dkg_finalize',
      [sessionId],
      (result) => FfiDkgComplete(
        address: result['address'] as String,
        publicKey: Uint8List.fromList(List<int>.from(result['public_key'])),
      ),
    );
  }

  /// Derive the backup shard (Party 2) from DKG round 2 evaluations.
  Future<Uint8List> dkgDeriveBackupShare(String sessionId, int backupPartyIndex) async {
    return _callNative<Uint8List>(
      'dkg_derive_backup_share',
      [sessionId, backupPartyIndex],
      (result) => Uint8List.fromList(List<int>.from(result)),
    );
  }

  // ---------------------------------------------------------------------------
  // Distributed Signing — 2-party ECDSA without key reconstruction
  // ---------------------------------------------------------------------------

  /// Initialize a distributed signing session and generate Round 1.
  Future<FfiSignRound1> signGenerateRound1(Uint8List msgHash) async {
    if (msgHash.length != 32) {
      throw ArgumentError('msg_hash must be 32 bytes');
    }
    return _callNative<FfiSignRound1>(
      'sign_generate_round1',
      [msgHash],
      (result) => FfiSignRound1(
        sessionId: result['session_id'] as String,
        payload: Uint8List.fromList(List<int>.from(result['payload'])),
        msgHash: Uint8List.fromList(List<int>.from(result['msg_hash'])),
      ),
    );
  }

  /// Process server's Round 1 response and generate device's Round 2.
  Future<Uint8List> signProcessRound1AndGenerateRound2(
    String sessionId,
    Uint8List serverRound1Payload,
  ) async {
    return _callNative<Uint8List>(
      'sign_process_round1_and_generate_round2',
      [sessionId, serverRound1Payload],
      (result) => Uint8List.fromList(List<int>.from(result)),
    );
  }

  /// Process server's Round 2 response and finalize signature.
  Future<FfiSignResult> signProcessRound2(
    String sessionId,
    Uint8List serverRound2Payload,
  ) async {
    return _callNative<FfiSignResult>(
      'sign_process_round2',
      [sessionId, serverRound2Payload],
      (result) => FfiSignResult(
        signature: Uint8List.fromList(List<int>.from(result['signature'])),
      ),
    );
  }

  /// Legacy: Sign locally for testing (reconstructs full key — NOT for production).
  Future<Uint8List> signHash(Uint8List msgHash) async {
    if (msgHash.length != 32) {
      throw ArgumentError('msg_hash must be 32 bytes');
    }
    return _callNative<Uint8List>(
      'sign_hash',
      [msgHash],
      (result) => Uint8List.fromList(List<int>.from(result)),
    );
  }

  // ---------------------------------------------------------------------------
  // Reshare Protocol — Proactive key refresh (preserves public key)
  // ---------------------------------------------------------------------------

  /// Initialize a reshare session using the current device shard.
  Future<FfiReshareSession> reshareSessionNew(int partyIndex) async {
    return _callNative<FfiReshareSession>(
      'reshare_session_new',
      [partyIndex],
      (result) => FfiReshareSession(
        sessionId: result['session_id'] as String,
      ),
    );
  }

  /// Generate reshare Round 1 messages.
  Future<FfiReshareRound1Result> reshareGenerateRound1(String sessionId) async {
    return _callNative<FfiReshareRound1Result>(
      'reshare_generate_round1',
      [sessionId],
      (result) => FfiReshareRound1Result(
        messagesJson: List<String>.from(result['messages_json'] as List),
      ),
    );
  }

  /// Process reshare Round 1 messages from other parties.
  Future<void> reshareProcessRound1(String sessionId, List<String> messagesJson) async {
    await _callNative<void>(
      'reshare_process_round1',
      [sessionId, messagesJson],
      (_) {},
    );
  }

  /// Finalize reshare: extract the new key share and replace the old one.
  Future<FfiReshareComplete> reshareFinalize(String sessionId) async {
    return _callNative<FfiReshareComplete>(
      'reshare_finalize',
      [sessionId],
      (result) => FfiReshareComplete(
        address: result['address'] as String,
        publicKey: Uint8List.fromList(List<int>.from(result['public_key'])),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Presign Protocol — Pre-compute signing material for instant signatures
  // ---------------------------------------------------------------------------

  /// Start a presign session: generate ephemeral k and Round 1.
  Future<FfiPresignRound1> presignGenerateRound1() async {
    return _callNative<FfiPresignRound1>(
      'presign_generate_round1',
      [],
      (result) => FfiPresignRound1(
        sessionId: result['session_id'] as String,
        payload: Uint8List.fromList(List<int>.from(result['payload'])),
      ),
    );
  }

  /// Process server's presign Round 1 and generate Round 2.
  Future<Uint8List> presignProcessRound1AndGenerateRound2(
    String sessionId,
    Uint8List serverRound1Payload,
  ) async {
    return _callNative<Uint8List>(
      'presign_process_round1_and_generate_round2',
      [sessionId, serverRound1Payload],
      (result) => Uint8List.fromList(List<int>.from(result)),
    );
  }

  /// Finalize presign: extract the presignature data for later use.
  Future<FfiPresignComplete> presignFinalize(String sessionId) async {
    return _callNative<FfiPresignComplete>(
      'presign_finalize',
      [sessionId],
      (result) => FfiPresignComplete(
        presigData: Uint8List.fromList(List<int>.from(result['presig_data'])),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Recovery Protocol — Restore device shard using backup + server shards
  // ---------------------------------------------------------------------------

  /// Import and validate the backup shard for recovery.
  Future<void> recoveryImportBackupShard(Uint8List backupBytes) async {
    if (backupBytes.length != 32) {
      throw ArgumentError('backup shard must be 32 bytes');
    }
    await _callNative<void>(
      'recovery_import_backup_shard',
      [backupBytes],
      (_) {},
    );
  }

  /// Reconstruct the device shard using backup shard + server contribution.
  Future<FfiDkgComplete> recoveryReconstructDeviceShard(
    String sessionId,
    List<String> serverMessagesJson,
    Uint8List publicKey,
  ) async {
    return _callNative<FfiDkgComplete>(
      'recovery_reconstruct_device_shard',
      [sessionId, serverMessagesJson, publicKey],
      (result) => FfiDkgComplete(
        address: result['address'] as String,
        publicKey: Uint8List.fromList(List<int>.from(result['public_key'])),
      ),
    );
  }

  /// Clear the temporary backup shard from recovery state.
  Future<void> recoveryClearBackupShard() async {
    await _callNative<void>(
      'recovery_clear_backup_shard',
      [],
      (_) {},
    );
  }

  /// Check if a backup shard has been imported for recovery.
  Future<bool> recoveryHasBackupShard() async {
    return _callNative<bool>(
      'recovery_has_backup_shard',
      [],
      (result) => result as bool,
    );
  }

  // ---------------------------------------------------------------------------
  // Balance queries (async, uses tokio)
  // ---------------------------------------------------------------------------

  /// Query ETH balance for an address.
  Future<FfiBalance> queryEthBalance(String address, String rpcUrl) async {
    return _callNative<FfiBalance>(
      'query_eth_balance',
      [address, rpcUrl],
      (result) => FfiBalance(
        wei: result['wei'] as String,
        formatted: result['formatted'] as String,
        decimals: result['decimals'] as int,
      ),
    );
  }

  /// Query ERC-20 token balance.
  Future<FfiBalance> queryTokenBalance(
    String owner,
    String tokenContract,
    String rpcUrl,
  ) async {
    return _callNative<FfiBalance>(
      'query_token_balance',
      [owner, tokenContract, rpcUrl],
      (result) => FfiBalance(
        wei: result['wei'] as String,
        formatted: result['formatted'] as String,
        decimals: result['decimals'] as int,
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Transaction building
  // ---------------------------------------------------------------------------

  /// Estimate gas for a transaction.
  Future<FfiGasEstimate> estimateGas(
    String from,
    String to,
    String valueWei,
    Uint8List? data,
    String rpcUrl,
  ) async {
    return _callNative<FfiGasEstimate>(
      'estimate_gas',
      [from, to, valueWei, data, rpcUrl],
      (result) => FfiGasEstimate(
        gasLimit: result['gas_limit'] as int,
        maxFeePerGas: result['max_fee_per_gas'] as String,
        maxPriorityFeePerGas: result['max_priority_fee_per_gas'] as String,
        estimatedCostWei: result['estimated_cost_wei'] as String,
      ),
    );
  }

  /// Build, sign, and broadcast an ETH transfer.
  Future<FfiTxResult> sendEth(
    String to,
    String valueWei,
    String rpcUrl,
  ) async {
    return _callNative<FfiTxResult>(
      'send_eth',
      [to, valueWei, rpcUrl],
      (result) => FfiTxResult(
        txHash: result['tx_hash'] as String,
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Internal: Native method channel placeholder
  // ---------------------------------------------------------------------------

  /// Placeholder for native FFI calls.
  /// In a real flutter_rust_bridge setup, this would use MethodChannel or dart:ffi.
  Future<T> _callNative<T>(
    String method,
    List<dynamic> args,
    T Function(dynamic) parser,
  ) async {
    // This is a stub. The actual implementation would:
    // 1. Use a MethodChannel to call into Rust via platform channels, OR
    // 2. Use dart:ffi to call Rust functions directly via shared library

    throw UnimplementedError(
      'Native FFI bridge not initialized. '
      'Run flutter_rust_bridge_codegen to generate the actual bindings.',
    );
  }
}

// ---------------------------------------------------------------------------
// Global API singleton (used by mpc_bridge.dart)
// ---------------------------------------------------------------------------

/// Global API instance for Rust FFI calls.
/// This is the main entry point used by the higher-level MpcBridge wrapper.
final Api api = Api();
