// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiBalance dco_decode_ffi_balance(dynamic raw);

  @protected
  FfiDkgComplete dco_decode_ffi_dkg_complete(dynamic raw);

  @protected
  FfiDkgSession dco_decode_ffi_dkg_session(dynamic raw);

  @protected
  FfiGasEstimate dco_decode_ffi_gas_estimate(dynamic raw);

  @protected
  FfiKeyStatus dco_decode_ffi_key_status(dynamic raw);

  @protected
  FfiPresignComplete dco_decode_ffi_presign_complete(dynamic raw);

  @protected
  FfiPresignRound1 dco_decode_ffi_presign_round_1(dynamic raw);

  @protected
  FfiReshareComplete dco_decode_ffi_reshare_complete(dynamic raw);

  @protected
  FfiReshareRound1Result dco_decode_ffi_reshare_round_1_result(dynamic raw);

  @protected
  FfiReshareSession dco_decode_ffi_reshare_session(dynamic raw);

  @protected
  FfiRound1Result dco_decode_ffi_round_1_result(dynamic raw);

  @protected
  FfiSignResult dco_decode_ffi_sign_result(dynamic raw);

  @protected
  FfiSignRound1 dco_decode_ffi_sign_round_1(dynamic raw);

  @protected
  FfiTxResult dco_decode_ffi_tx_result(dynamic raw);

  @protected
  FfiWalletInfo dco_decode_ffi_wallet_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiBalance sse_decode_ffi_balance(SseDeserializer deserializer);

  @protected
  FfiDkgComplete sse_decode_ffi_dkg_complete(SseDeserializer deserializer);

  @protected
  FfiDkgSession sse_decode_ffi_dkg_session(SseDeserializer deserializer);

  @protected
  FfiGasEstimate sse_decode_ffi_gas_estimate(SseDeserializer deserializer);

  @protected
  FfiKeyStatus sse_decode_ffi_key_status(SseDeserializer deserializer);

  @protected
  FfiPresignComplete sse_decode_ffi_presign_complete(
    SseDeserializer deserializer,
  );

  @protected
  FfiPresignRound1 sse_decode_ffi_presign_round_1(SseDeserializer deserializer);

  @protected
  FfiReshareComplete sse_decode_ffi_reshare_complete(
    SseDeserializer deserializer,
  );

  @protected
  FfiReshareRound1Result sse_decode_ffi_reshare_round_1_result(
    SseDeserializer deserializer,
  );

  @protected
  FfiReshareSession sse_decode_ffi_reshare_session(
    SseDeserializer deserializer,
  );

  @protected
  FfiRound1Result sse_decode_ffi_round_1_result(SseDeserializer deserializer);

  @protected
  FfiSignResult sse_decode_ffi_sign_result(SseDeserializer deserializer);

  @protected
  FfiSignRound1 sse_decode_ffi_sign_round_1(SseDeserializer deserializer);

  @protected
  FfiTxResult sse_decode_ffi_tx_result(SseDeserializer deserializer);

  @protected
  FfiWalletInfo sse_decode_ffi_wallet_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_balance(FfiBalance self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_dkg_complete(
    FfiDkgComplete self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_dkg_session(FfiDkgSession self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_gas_estimate(
    FfiGasEstimate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_key_status(FfiKeyStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_presign_complete(
    FfiPresignComplete self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_presign_round_1(
    FfiPresignRound1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_reshare_complete(
    FfiReshareComplete self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_reshare_round_1_result(
    FfiReshareRound1Result self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_reshare_session(
    FfiReshareSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_round_1_result(
    FfiRound1Result self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_sign_result(FfiSignResult self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_sign_round_1(
    FfiSignRound1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_tx_result(FfiTxResult self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_wallet_info(FfiWalletInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
