// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_gas_estimate`, `get_signing_shares`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FfiRound2Result`, `PresignData`

/// Generate a new MPC wallet using local-mode TSS (2-of-3).
/// Returns the derived Ethereum address and public key.
/// The 3 key shares are stored in Rust memory — NEVER sent to Dart.
Future<FfiWalletInfo> generateWallet() =>
    RustLib.instance.api.crateApiGenerateWallet();

/// Check if wallet shares are loaded in memory.
Future<bool> hasWallet() => RustLib.instance.api.crateApiHasWallet();

/// Get the key status for the UI (which shards are present).
Future<FfiKeyStatus> getKeyStatus() =>
    RustLib.instance.api.crateApiGetKeyStatus();

/// Clear all shares from memory (for wallet deletion / reset).
Future<void> clearWallet() => RustLib.instance.api.crateApiClearWallet();

/// Initialize a new DKG session.
/// Returns the session_id to use for subsequent calls.
Future<FfiDkgSession> dkgSessionNew({required int partyIndex}) =>
    RustLib.instance.api.crateApiDkgSessionNew(partyIndex: partyIndex);

/// DKG Round 1: Generate commitments to VSS polynomial.
/// Returns the broadcast message as JSON.
Future<FfiRound1Result> dkgGenerateRound1({required String sessionId}) =>
    RustLib.instance.api.crateApiDkgGenerateRound1(sessionId: sessionId);

/// DKG Round 1: Process all commitments from other parties.
Future<void> dkgProcessRound1({
  required String sessionId,
  required List<String> messagesJson,
}) => RustLib.instance.api.crateApiDkgProcessRound1(
  sessionId: sessionId,
  messagesJson: messagesJson,
);

/// DKG Round 2: Generate secret share evaluations.
/// Returns the message(s) to send to other parties as JSON.
Future<List<String>> dkgGenerateRound2({required String sessionId}) =>
    RustLib.instance.api.crateApiDkgGenerateRound2(sessionId: sessionId);

/// DKG Round 2: Process share evaluations from other parties.
Future<void> dkgProcessRound2({
  required String sessionId,
  required List<String> messagesJson,
}) => RustLib.instance.api.crateApiDkgProcessRound2(
  sessionId: sessionId,
  messagesJson: messagesJson,
);

/// Finalize DKG and extract the key share.
/// Stores the key shares in memory for later signing.
/// Does NOT delete the DKG session — call dkg_derive_backup_share first if needed.
Future<FfiDkgComplete> dkgFinalize({required String sessionId}) =>
    RustLib.instance.api.crateApiDkgFinalize(sessionId: sessionId);

/// Derive the backup shard (Party 2) from DKG round 2 evaluations.
/// Must be called AFTER dkg_finalize but BEFORE the session is cleaned up.
/// Returns the raw 32-byte secret share for the backup party.
Future<Uint8List> dkgDeriveBackupShare({
  required String sessionId,
  required int backupPartyIndex,
}) => RustLib.instance.api.crateApiDkgDeriveBackupShare(
  sessionId: sessionId,
  backupPartyIndex: backupPartyIndex,
);

/// Combine two backup share contributions into the final backup shard.
/// Adds device_share + server_share modulo the secp256k1 curve order.
/// Both inputs must be exactly 32 bytes.
Future<Uint8List> combineBackupShares({
  required List<int> deviceShare,
  required List<int> serverShare,
}) => RustLib.instance.api.crateApiCombineBackupShares(
  deviceShare: deviceShare,
  serverShare: serverShare,
);

/// Initialize a distributed signing session and generate Round 1 (R_0 = k_0*G).
/// Returns the payload to send to the server.
Future<FfiSignRound1> signGenerateRound1({required List<int> msgHash}) =>
    RustLib.instance.api.crateApiSignGenerateRound1(msgHash: msgHash);

/// Process server's Round 1 response (R_1) and generate device's Round 2 contribution.
/// Returns the DeviceContribution payload to send to server.
Future<Uint8List> signProcessRound1AndGenerateRound2({
  required String sessionId,
  required List<int> serverRound1Payload,
}) => RustLib.instance.api.crateApiSignProcessRound1AndGenerateRound2(
  sessionId: sessionId,
  serverRound1Payload: serverRound1Payload,
);

/// Process server's Round 2 response (ServerSignature containing s).
/// Returns the final 65-byte signature.
Future<FfiSignResult> signProcessRound2({
  required String sessionId,
  required List<int> serverRound2Payload,
}) => RustLib.instance.api.crateApiSignProcessRound2(
  sessionId: sessionId,
  serverRound2Payload: serverRound2Payload,
);

/// Initialize a reshare session using the current device shard.
/// The old shard is consumed; after finalize() the new shard replaces it.
Future<FfiReshareSession> reshareSessionNew({required int partyIndex}) =>
    RustLib.instance.api.crateApiReshareSessionNew(partyIndex: partyIndex);

/// Generate reshare Round 1 messages (new VSS polynomial evaluations for each party).
/// Returns serialized ProtocolMessages to send to other parties.
Future<FfiReshareRound1Result> reshareGenerateRound1({
  required String sessionId,
}) => RustLib.instance.api.crateApiReshareGenerateRound1(sessionId: sessionId);

/// Process reshare Round 1 messages from other parties and compute new key share.
Future<void> reshareProcessRound1({
  required String sessionId,
  required List<String> messagesJson,
}) => RustLib.instance.api.crateApiReshareProcessRound1(
  sessionId: sessionId,
  messagesJson: messagesJson,
);

/// Finalize reshare: extract the new key share and replace the old one in memory.
/// After this call, the old share is invalid and the new share is active.
Future<FfiReshareComplete> reshareFinalize({required String sessionId}) =>
    RustLib.instance.api.crateApiReshareFinalize(sessionId: sessionId);

/// Start a presign session: generate ephemeral k and Round 1 (R_0 = k_0*G).
/// Similar to sign_generate_round1 but without a message hash (computed later).
Future<FfiPresignRound1> presignGenerateRound1() =>
    RustLib.instance.api.crateApiPresignGenerateRound1();

/// Process server's presign Round 1 (R_1) and generate Round 2.
/// Returns the DeviceContribution payload.
Future<Uint8List> presignProcessRound1AndGenerateRound2({
  required String sessionId,
  required List<int> serverRound1Payload,
}) => RustLib.instance.api.crateApiPresignProcessRound1AndGenerateRound2(
  sessionId: sessionId,
  serverRound1Payload: serverRound1Payload,
);

/// Finalize presign: extract the presignature data for later use.
/// The presign data is an opaque blob containing (k_0, R) that will be
/// combined with the actual message hash at sign time.
Future<FfiPresignComplete> presignFinalize({required String sessionId}) =>
    RustLib.instance.api.crateApiPresignFinalize(sessionId: sessionId);

/// Import and validate the backup shard for recovery.
/// The backup shard is stored temporarily until recovery is complete.
Future<void> recoveryImportBackupShard({required List<int> backupBytes}) =>
    RustLib.instance.api.crateApiRecoveryImportBackupShard(
      backupBytes: backupBytes,
    );

/// Reconstruct the device shard (Party 0) using backup shard + server contribution.
///
/// Recovery flow:
/// 1. User authenticates and server fetches its shard (Party 1)
/// 2. User provides backup shard (Party 2)
/// 3. Server initiates a special reshare where Party 0 is reconstructed
/// 4. The backup + server shards generate a new device shard without changing the public key
Future<FfiDkgComplete> recoveryReconstructDeviceShard({
  required String sessionId,
  required List<String> serverMessagesJson,
  required List<int> publicKey,
}) => RustLib.instance.api.crateApiRecoveryReconstructDeviceShard(
  sessionId: sessionId,
  serverMessagesJson: serverMessagesJson,
  publicKey: publicKey,
);

/// Clear the temporary backup shard from recovery state.
Future<void> recoveryClearBackupShard() =>
    RustLib.instance.api.crateApiRecoveryClearBackupShard();

/// Check if a backup shard has been imported for recovery.
Future<bool> recoveryHasBackupShard() =>
    RustLib.instance.api.crateApiRecoveryHasBackupShard();

/// Legacy: Sign locally for testing (reconstructs full key — NOT for production).
Future<Uint8List> signHash({required List<int> msgHash}) =>
    RustLib.instance.api.crateApiSignHash(msgHash: msgHash);

/// Query ETH balance for an address on Base Sepolia.
/// Returns balance in wei as a decimal string.
Future<FfiBalance> queryEthBalance({
  required String address,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiQueryEthBalance(
  address: address,
  rpcUrl: rpcUrl,
);

/// Query ERC-20 token balance.
Future<FfiBalance> queryTokenBalance({
  required String owner,
  required String tokenContract,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiQueryTokenBalance(
  owner: owner,
  tokenContract: tokenContract,
  rpcUrl: rpcUrl,
);

/// Estimate gas for a transaction.
Future<FfiGasEstimate> estimateGas({
  required String from,
  required String to,
  required String valueWei,
  Uint8List? data,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiEstimateGas(
  from: from,
  to: to,
  valueWei: valueWei,
  data: data,
  rpcUrl: rpcUrl,
);

/// Build, sign, and broadcast an ETH transfer.
/// Biometric auth must happen on the Dart side BEFORE calling this.
Future<FfiTxResult> sendEth({
  required String to,
  required String valueWei,
  required BigInt chainId,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiSendEth(
  to: to,
  valueWei: valueWei,
  chainId: chainId,
  rpcUrl: rpcUrl,
);

/// Build, sign, and broadcast an ERC-20 token transfer.
Future<FfiTxResult> sendErc20({
  required String to,
  required String tokenContract,
  required String amountRaw,
  required BigInt chainId,
  required String rpcUrl,
}) => RustLib.instance.api.crateApiSendErc20(
  to: to,
  tokenContract: tokenContract,
  amountRaw: amountRaw,
  chainId: chainId,
  rpcUrl: rpcUrl,
);

class FfiBalance {
  final String wei;
  final String formatted;
  final int decimals;

  const FfiBalance({
    required this.wei,
    required this.formatted,
    required this.decimals,
  });

  @override
  int get hashCode => wei.hashCode ^ formatted.hashCode ^ decimals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiBalance &&
          runtimeType == other.runtimeType &&
          wei == other.wei &&
          formatted == other.formatted &&
          decimals == other.decimals;
}

class FfiDkgComplete {
  /// Wallet address (0x-prefixed hex)
  final String address;

  /// Public key (compressed SEC1 format)
  final Uint8List publicKey;

  const FfiDkgComplete({required this.address, required this.publicKey});

  @override
  int get hashCode => address.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDkgComplete &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          publicKey == other.publicKey;
}

class FfiDkgSession {
  /// Session ID for message routing
  final String sessionId;

  const FfiDkgSession({required this.sessionId});

  @override
  int get hashCode => sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDkgSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId;
}

class FfiGasEstimate {
  final BigInt gasLimit;
  final String maxFeePerGas;
  final String maxPriorityFeePerGas;
  final String estimatedCostWei;

  const FfiGasEstimate({
    required this.gasLimit,
    required this.maxFeePerGas,
    required this.maxPriorityFeePerGas,
    required this.estimatedCostWei,
  });

  @override
  int get hashCode =>
      gasLimit.hashCode ^
      maxFeePerGas.hashCode ^
      maxPriorityFeePerGas.hashCode ^
      estimatedCostWei.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiGasEstimate &&
          runtimeType == other.runtimeType &&
          gasLimit == other.gasLimit &&
          maxFeePerGas == other.maxFeePerGas &&
          maxPriorityFeePerGas == other.maxPriorityFeePerGas &&
          estimatedCostWei == other.estimatedCostWei;
}

class FfiKeyStatus {
  final bool hasDeviceShard;
  final bool hasServerShard;
  final bool hasBackupShard;
  final String address;

  const FfiKeyStatus({
    required this.hasDeviceShard,
    required this.hasServerShard,
    required this.hasBackupShard,
    required this.address,
  });

  @override
  int get hashCode =>
      hasDeviceShard.hashCode ^
      hasServerShard.hashCode ^
      hasBackupShard.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiKeyStatus &&
          runtimeType == other.runtimeType &&
          hasDeviceShard == other.hasDeviceShard &&
          hasServerShard == other.hasServerShard &&
          hasBackupShard == other.hasBackupShard &&
          address == other.address;
}

class FfiPresignComplete {
  /// Serialized presignature data (opaque blob, stored encrypted on server)
  final Uint8List presigData;

  const FfiPresignComplete({required this.presigData});

  @override
  int get hashCode => presigData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPresignComplete &&
          runtimeType == other.runtimeType &&
          presigData == other.presigData;
}

class FfiPresignRound1 {
  final String sessionId;
  final Uint8List payload;

  const FfiPresignRound1({required this.sessionId, required this.payload});

  @override
  int get hashCode => sessionId.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPresignRound1 &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          payload == other.payload;
}

class FfiReshareComplete {
  final String address;
  final Uint8List publicKey;

  const FfiReshareComplete({required this.address, required this.publicKey});

  @override
  int get hashCode => address.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiReshareComplete &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          publicKey == other.publicKey;
}

class FfiReshareRound1Result {
  /// JSON-serialized list of ProtocolMessages (one per party)
  final List<String> messagesJson;

  const FfiReshareRound1Result({required this.messagesJson});

  @override
  int get hashCode => messagesJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiReshareRound1Result &&
          runtimeType == other.runtimeType &&
          messagesJson == other.messagesJson;
}

class FfiReshareSession {
  final String sessionId;

  const FfiReshareSession({required this.sessionId});

  @override
  int get hashCode => sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiReshareSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId;
}

class FfiRound1Result {
  /// Serialized ProtocolMessage (JSON)
  final String messageJson;

  const FfiRound1Result({required this.messageJson});

  @override
  int get hashCode => messageJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRound1Result &&
          runtimeType == other.runtimeType &&
          messageJson == other.messageJson;
}

class FfiSignResult {
  /// 65-byte signature (r[32] || s[32] || v[1])
  final Uint8List signature;

  const FfiSignResult({required this.signature});

  @override
  int get hashCode => signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSignResult &&
          runtimeType == other.runtimeType &&
          signature == other.signature;
}

class FfiSignRound1 {
  /// Session ID for routing subsequent rounds
  final String sessionId;

  /// Serialized Round 1 payload (bincode of SignRound1Message) to send to server
  final Uint8List payload;

  /// The message hash included for the server
  final Uint8List msgHash;

  const FfiSignRound1({
    required this.sessionId,
    required this.payload,
    required this.msgHash,
  });

  @override
  int get hashCode => sessionId.hashCode ^ payload.hashCode ^ msgHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSignRound1 &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          payload == other.payload &&
          msgHash == other.msgHash;
}

class FfiTxResult {
  final String txHash;

  const FfiTxResult({required this.txHash});

  @override
  int get hashCode => txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiTxResult &&
          runtimeType == other.runtimeType &&
          txHash == other.txHash;
}

class FfiWalletInfo {
  final String address;
  final Uint8List publicKey;

  const FfiWalletInfo({required this.address, required this.publicKey});

  @override
  int get hashCode => address.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiWalletInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          publicKey == other.publicKey;
}
