// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -910282382;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ffi_mobile',
        ioDirectory: '../crates/ffi-mobile/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiClearWallet();

  Future<Uint8List> crateApiCombineBackupShares({
    required List<int> deviceShare,
    required List<int> serverShare,
  });

  Future<Uint8List> crateApiDkgDeriveBackupShare({
    required String sessionId,
    required int backupPartyIndex,
  });

  Future<FfiDkgComplete> crateApiDkgFinalize({required String sessionId});

  Future<FfiRound1Result> crateApiDkgGenerateRound1({
    required String sessionId,
  });

  Future<List<String>> crateApiDkgGenerateRound2({required String sessionId});

  Future<void> crateApiDkgProcessRound1({
    required String sessionId,
    required List<String> messagesJson,
  });

  Future<void> crateApiDkgProcessRound2({
    required String sessionId,
    required List<String> messagesJson,
  });

  Future<FfiDkgSession> crateApiDkgSessionNew({required int partyIndex});

  Future<FfiGasEstimate> crateApiEstimateGas({
    required String from,
    required String to,
    required String valueWei,
    Uint8List? data,
    required String rpcUrl,
  });

  Future<String> crateApiExportBackupShard({required String password});

  Future<Uint8List> crateApiExportDeviceShard();

  Future<FfiWalletInfo> crateApiGenerateWallet();

  Future<FfiKeyStatus> crateApiGetKeyStatus();

  Future<bool> crateApiHasWallet();

  Future<bool> crateApiImportBackupShard({
    required String encryptedData,
    required String password,
  });

  Future<void> crateApiImportDeviceShard({
    required List<int> shardBytes,
    required List<int> publicKey,
  });

  Future<FfiPresignComplete> crateApiPresignFinalize({
    required String sessionId,
  });

  Future<FfiPresignRound1> crateApiPresignGenerateRound1();

  Future<Uint8List> crateApiPresignProcessRound1AndGenerateRound2({
    required String sessionId,
    required List<int> serverRound1Payload,
  });

  Future<FfiBalance> crateApiQueryEthBalance({
    required String address,
    required String rpcUrl,
  });

  Future<FfiBalance> crateApiQueryTokenBalance({
    required String owner,
    required String tokenContract,
    required String rpcUrl,
  });

  Future<void> crateApiRecoveryClearBackupShard();

  Future<bool> crateApiRecoveryHasBackupShard();

  Future<void> crateApiRecoveryImportBackupShard({
    required List<int> backupBytes,
  });

  Future<FfiDkgComplete> crateApiRecoveryReconstructDeviceShard({
    required String sessionId,
    required List<String> serverMessagesJson,
    required List<int> publicKey,
  });

  Future<FfiReshareComplete> crateApiReshareFinalize({
    required String sessionId,
  });

  Future<FfiReshareRound1Result> crateApiReshareGenerateRound1({
    required String sessionId,
  });

  Future<void> crateApiReshareProcessRound1({
    required String sessionId,
    required List<String> messagesJson,
  });

  Future<FfiReshareSession> crateApiReshareSessionNew({
    required int partyIndex,
  });

  Future<FfiTxResult> crateApiSendErc20({
    required String to,
    required String tokenContract,
    required String amountRaw,
    required BigInt chainId,
    required String rpcUrl,
  });

  Future<FfiTxResult> crateApiSendEth({
    required String to,
    required String valueWei,
    required BigInt chainId,
    required String rpcUrl,
  });

  Future<FfiSignRound1> crateApiSignGenerateRound1({
    required List<int> msgHash,
  });

  Future<Uint8List> crateApiSignHash({required List<int> msgHash});

  Future<Uint8List> crateApiSignProcessRound1AndGenerateRound2({
    required String sessionId,
    required List<int> serverRound1Payload,
  });

  Future<FfiSignResult> crateApiSignProcessRound2({
    required String sessionId,
    required List<int> serverRound2Payload,
  });

  Future<bool> crateApiVerifyBackupShard({
    required List<int> backupBytes,
    required List<int> deviceShardBytes,
    required List<int> expectedPublicKey,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiClearWallet() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClearWalletConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearWalletConstMeta =>
      const TaskConstMeta(debugName: "clear_wallet", argNames: []);

  @override
  Future<Uint8List> crateApiCombineBackupShares({
    required List<int> deviceShare,
    required List<int> serverShare,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(deviceShare, serializer);
          sse_encode_list_prim_u_8_loose(serverShare, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCombineBackupSharesConstMeta,
        argValues: [deviceShare, serverShare],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCombineBackupSharesConstMeta =>
      const TaskConstMeta(
        debugName: "combine_backup_shares",
        argNames: ["deviceShare", "serverShare"],
      );

  @override
  Future<Uint8List> crateApiDkgDeriveBackupShare({
    required String sessionId,
    required int backupPartyIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(backupPartyIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgDeriveBackupShareConstMeta,
        argValues: [sessionId, backupPartyIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgDeriveBackupShareConstMeta =>
      const TaskConstMeta(
        debugName: "dkg_derive_backup_share",
        argNames: ["sessionId", "backupPartyIndex"],
      );

  @override
  Future<FfiDkgComplete> crateApiDkgFinalize({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_dkg_complete,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgFinalizeConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgFinalizeConstMeta =>
      const TaskConstMeta(debugName: "dkg_finalize", argNames: ["sessionId"]);

  @override
  Future<FfiRound1Result> crateApiDkgGenerateRound1({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_round_1_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgGenerateRound1ConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgGenerateRound1ConstMeta => const TaskConstMeta(
    debugName: "dkg_generate_round1",
    argNames: ["sessionId"],
  );

  @override
  Future<List<String>> crateApiDkgGenerateRound2({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgGenerateRound2ConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgGenerateRound2ConstMeta => const TaskConstMeta(
    debugName: "dkg_generate_round2",
    argNames: ["sessionId"],
  );

  @override
  Future<void> crateApiDkgProcessRound1({
    required String sessionId,
    required List<String> messagesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_String(messagesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgProcessRound1ConstMeta,
        argValues: [sessionId, messagesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgProcessRound1ConstMeta => const TaskConstMeta(
    debugName: "dkg_process_round1",
    argNames: ["sessionId", "messagesJson"],
  );

  @override
  Future<void> crateApiDkgProcessRound2({
    required String sessionId,
    required List<String> messagesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_String(messagesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgProcessRound2ConstMeta,
        argValues: [sessionId, messagesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgProcessRound2ConstMeta => const TaskConstMeta(
    debugName: "dkg_process_round2",
    argNames: ["sessionId", "messagesJson"],
  );

  @override
  Future<FfiDkgSession> crateApiDkgSessionNew({required int partyIndex}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(partyIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_dkg_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDkgSessionNewConstMeta,
        argValues: [partyIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDkgSessionNewConstMeta => const TaskConstMeta(
    debugName: "dkg_session_new",
    argNames: ["partyIndex"],
  );

  @override
  Future<FfiGasEstimate> crateApiEstimateGas({
    required String from,
    required String to,
    required String valueWei,
    Uint8List? data,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          sse_encode_String(valueWei, serializer);
          sse_encode_opt_list_prim_u_8_strict(data, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_gas_estimate,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEstimateGasConstMeta,
        argValues: [from, to, valueWei, data, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEstimateGasConstMeta => const TaskConstMeta(
    debugName: "estimate_gas",
    argNames: ["from", "to", "valueWei", "data", "rpcUrl"],
  );

  @override
  Future<String> crateApiExportBackupShard({required String password}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportBackupShardConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportBackupShardConstMeta => const TaskConstMeta(
    debugName: "export_backup_shard",
    argNames: ["password"],
  );

  @override
  Future<Uint8List> crateApiExportDeviceShard() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportDeviceShardConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportDeviceShardConstMeta =>
      const TaskConstMeta(debugName: "export_device_shard", argNames: []);

  @override
  Future<FfiWalletInfo> crateApiGenerateWallet() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_wallet_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateWalletConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateWalletConstMeta =>
      const TaskConstMeta(debugName: "generate_wallet", argNames: []);

  @override
  Future<FfiKeyStatus> crateApiGetKeyStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_key_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetKeyStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetKeyStatusConstMeta =>
      const TaskConstMeta(debugName: "get_key_status", argNames: []);

  @override
  Future<bool> crateApiHasWallet() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHasWalletConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHasWalletConstMeta =>
      const TaskConstMeta(debugName: "has_wallet", argNames: []);

  @override
  Future<bool> crateApiImportBackupShard({
    required String encryptedData,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(encryptedData, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportBackupShardConstMeta,
        argValues: [encryptedData, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportBackupShardConstMeta => const TaskConstMeta(
    debugName: "import_backup_shard",
    argNames: ["encryptedData", "password"],
  );

  @override
  Future<void> crateApiImportDeviceShard({
    required List<int> shardBytes,
    required List<int> publicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(shardBytes, serializer);
          sse_encode_list_prim_u_8_loose(publicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportDeviceShardConstMeta,
        argValues: [shardBytes, publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportDeviceShardConstMeta => const TaskConstMeta(
    debugName: "import_device_shard",
    argNames: ["shardBytes", "publicKey"],
  );

  @override
  Future<FfiPresignComplete> crateApiPresignFinalize({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_presign_complete,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPresignFinalizeConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPresignFinalizeConstMeta => const TaskConstMeta(
    debugName: "presign_finalize",
    argNames: ["sessionId"],
  );

  @override
  Future<FfiPresignRound1> crateApiPresignGenerateRound1() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_presign_round_1,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPresignGenerateRound1ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPresignGenerateRound1ConstMeta =>
      const TaskConstMeta(debugName: "presign_generate_round1", argNames: []);

  @override
  Future<Uint8List> crateApiPresignProcessRound1AndGenerateRound2({
    required String sessionId,
    required List<int> serverRound1Payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(serverRound1Payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPresignProcessRound1AndGenerateRound2ConstMeta,
        argValues: [sessionId, serverRound1Payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPresignProcessRound1AndGenerateRound2ConstMeta =>
      const TaskConstMeta(
        debugName: "presign_process_round1_and_generate_round2",
        argNames: ["sessionId", "serverRound1Payload"],
      );

  @override
  Future<FfiBalance> crateApiQueryEthBalance({
    required String address,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_balance,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQueryEthBalanceConstMeta,
        argValues: [address, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryEthBalanceConstMeta => const TaskConstMeta(
    debugName: "query_eth_balance",
    argNames: ["address", "rpcUrl"],
  );

  @override
  Future<FfiBalance> crateApiQueryTokenBalance({
    required String owner,
    required String tokenContract,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(owner, serializer);
          sse_encode_String(tokenContract, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_balance,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQueryTokenBalanceConstMeta,
        argValues: [owner, tokenContract, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQueryTokenBalanceConstMeta => const TaskConstMeta(
    debugName: "query_token_balance",
    argNames: ["owner", "tokenContract", "rpcUrl"],
  );

  @override
  Future<void> crateApiRecoveryClearBackupShard() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRecoveryClearBackupShardConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryClearBackupShardConstMeta =>
      const TaskConstMeta(
        debugName: "recovery_clear_backup_shard",
        argNames: [],
      );

  @override
  Future<bool> crateApiRecoveryHasBackupShard() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRecoveryHasBackupShardConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryHasBackupShardConstMeta =>
      const TaskConstMeta(debugName: "recovery_has_backup_shard", argNames: []);

  @override
  Future<void> crateApiRecoveryImportBackupShard({
    required List<int> backupBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(backupBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRecoveryImportBackupShardConstMeta,
        argValues: [backupBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryImportBackupShardConstMeta =>
      const TaskConstMeta(
        debugName: "recovery_import_backup_shard",
        argNames: ["backupBytes"],
      );

  @override
  Future<FfiDkgComplete> crateApiRecoveryReconstructDeviceShard({
    required String sessionId,
    required List<String> serverMessagesJson,
    required List<int> publicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_String(serverMessagesJson, serializer);
          sse_encode_list_prim_u_8_loose(publicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_dkg_complete,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRecoveryReconstructDeviceShardConstMeta,
        argValues: [sessionId, serverMessagesJson, publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoveryReconstructDeviceShardConstMeta =>
      const TaskConstMeta(
        debugName: "recovery_reconstruct_device_shard",
        argNames: ["sessionId", "serverMessagesJson", "publicKey"],
      );

  @override
  Future<FfiReshareComplete> crateApiReshareFinalize({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_reshare_complete,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReshareFinalizeConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReshareFinalizeConstMeta => const TaskConstMeta(
    debugName: "reshare_finalize",
    argNames: ["sessionId"],
  );

  @override
  Future<FfiReshareRound1Result> crateApiReshareGenerateRound1({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_reshare_round_1_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReshareGenerateRound1ConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReshareGenerateRound1ConstMeta =>
      const TaskConstMeta(
        debugName: "reshare_generate_round1",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiReshareProcessRound1({
    required String sessionId,
    required List<String> messagesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_String(messagesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReshareProcessRound1ConstMeta,
        argValues: [sessionId, messagesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReshareProcessRound1ConstMeta =>
      const TaskConstMeta(
        debugName: "reshare_process_round1",
        argNames: ["sessionId", "messagesJson"],
      );

  @override
  Future<FfiReshareSession> crateApiReshareSessionNew({
    required int partyIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(partyIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_reshare_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReshareSessionNewConstMeta,
        argValues: [partyIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReshareSessionNewConstMeta => const TaskConstMeta(
    debugName: "reshare_session_new",
    argNames: ["partyIndex"],
  );

  @override
  Future<FfiTxResult> crateApiSendErc20({
    required String to,
    required String tokenContract,
    required String amountRaw,
    required BigInt chainId,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(to, serializer);
          sse_encode_String(tokenContract, serializer);
          sse_encode_String(amountRaw, serializer);
          sse_encode_u_64(chainId, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_tx_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendErc20ConstMeta,
        argValues: [to, tokenContract, amountRaw, chainId, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendErc20ConstMeta => const TaskConstMeta(
    debugName: "send_erc20",
    argNames: ["to", "tokenContract", "amountRaw", "chainId", "rpcUrl"],
  );

  @override
  Future<FfiTxResult> crateApiSendEth({
    required String to,
    required String valueWei,
    required BigInt chainId,
    required String rpcUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(to, serializer);
          sse_encode_String(valueWei, serializer);
          sse_encode_u_64(chainId, serializer);
          sse_encode_String(rpcUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_tx_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendEthConstMeta,
        argValues: [to, valueWei, chainId, rpcUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendEthConstMeta => const TaskConstMeta(
    debugName: "send_eth",
    argNames: ["to", "valueWei", "chainId", "rpcUrl"],
  );

  @override
  Future<FfiSignRound1> crateApiSignGenerateRound1({
    required List<int> msgHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(msgHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_sign_round_1,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignGenerateRound1ConstMeta,
        argValues: [msgHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignGenerateRound1ConstMeta => const TaskConstMeta(
    debugName: "sign_generate_round1",
    argNames: ["msgHash"],
  );

  @override
  Future<Uint8List> crateApiSignHash({required List<int> msgHash}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(msgHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignHashConstMeta,
        argValues: [msgHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignHashConstMeta =>
      const TaskConstMeta(debugName: "sign_hash", argNames: ["msgHash"]);

  @override
  Future<Uint8List> crateApiSignProcessRound1AndGenerateRound2({
    required String sessionId,
    required List<int> serverRound1Payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(serverRound1Payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignProcessRound1AndGenerateRound2ConstMeta,
        argValues: [sessionId, serverRound1Payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignProcessRound1AndGenerateRound2ConstMeta =>
      const TaskConstMeta(
        debugName: "sign_process_round1_and_generate_round2",
        argNames: ["sessionId", "serverRound1Payload"],
      );

  @override
  Future<FfiSignResult> crateApiSignProcessRound2({
    required String sessionId,
    required List<int> serverRound2Payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(serverRound2Payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_sign_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignProcessRound2ConstMeta,
        argValues: [sessionId, serverRound2Payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignProcessRound2ConstMeta => const TaskConstMeta(
    debugName: "sign_process_round2",
    argNames: ["sessionId", "serverRound2Payload"],
  );

  @override
  Future<bool> crateApiVerifyBackupShard({
    required List<int> backupBytes,
    required List<int> deviceShardBytes,
    required List<int> expectedPublicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(backupBytes, serializer);
          sse_encode_list_prim_u_8_loose(deviceShardBytes, serializer);
          sse_encode_list_prim_u_8_loose(expectedPublicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVerifyBackupShardConstMeta,
        argValues: [backupBytes, deviceShardBytes, expectedPublicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyBackupShardConstMeta => const TaskConstMeta(
    debugName: "verify_backup_shard",
    argNames: ["backupBytes", "deviceShardBytes", "expectedPublicKey"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiBalance dco_decode_ffi_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiBalance(
      wei: dco_decode_String(arr[0]),
      formatted: dco_decode_String(arr[1]),
      decimals: dco_decode_u_8(arr[2]),
    );
  }

  @protected
  FfiDkgComplete dco_decode_ffi_dkg_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiDkgComplete(
      address: dco_decode_String(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  FfiDkgSession dco_decode_ffi_dkg_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiDkgSession(sessionId: dco_decode_String(arr[0]));
  }

  @protected
  FfiGasEstimate dco_decode_ffi_gas_estimate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiGasEstimate(
      gasLimit: dco_decode_u_64(arr[0]),
      maxFeePerGas: dco_decode_String(arr[1]),
      maxPriorityFeePerGas: dco_decode_String(arr[2]),
      estimatedCostWei: dco_decode_String(arr[3]),
    );
  }

  @protected
  FfiKeyStatus dco_decode_ffi_key_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiKeyStatus(
      hasDeviceShard: dco_decode_bool(arr[0]),
      hasServerShard: dco_decode_bool(arr[1]),
      hasBackupShard: dco_decode_bool(arr[2]),
      address: dco_decode_String(arr[3]),
    );
  }

  @protected
  FfiPresignComplete dco_decode_ffi_presign_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiPresignComplete(
      presigData: dco_decode_list_prim_u_8_strict(arr[0]),
    );
  }

  @protected
  FfiPresignRound1 dco_decode_ffi_presign_round_1(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiPresignRound1(
      sessionId: dco_decode_String(arr[0]),
      payload: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  FfiReshareComplete dco_decode_ffi_reshare_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiReshareComplete(
      address: dco_decode_String(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  FfiReshareRound1Result dco_decode_ffi_reshare_round_1_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiReshareRound1Result(messagesJson: dco_decode_list_String(arr[0]));
  }

  @protected
  FfiReshareSession dco_decode_ffi_reshare_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiReshareSession(sessionId: dco_decode_String(arr[0]));
  }

  @protected
  FfiRound1Result dco_decode_ffi_round_1_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiRound1Result(messageJson: dco_decode_String(arr[0]));
  }

  @protected
  FfiSignResult dco_decode_ffi_sign_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiSignResult(signature: dco_decode_list_prim_u_8_strict(arr[0]));
  }

  @protected
  FfiSignRound1 dco_decode_ffi_sign_round_1(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiSignRound1(
      sessionId: dco_decode_String(arr[0]),
      payload: dco_decode_list_prim_u_8_strict(arr[1]),
      msgHash: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  FfiTxResult dco_decode_ffi_tx_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiTxResult(txHash: dco_decode_String(arr[0]));
  }

  @protected
  FfiWalletInfo dco_decode_ffi_wallet_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiWalletInfo(
      address: dco_decode_String(arr[0]),
      publicKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiBalance sse_decode_ffi_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wei = sse_decode_String(deserializer);
    var var_formatted = sse_decode_String(deserializer);
    var var_decimals = sse_decode_u_8(deserializer);
    return FfiBalance(
      wei: var_wei,
      formatted: var_formatted,
      decimals: var_decimals,
    );
  }

  @protected
  FfiDkgComplete sse_decode_ffi_dkg_complete(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiDkgComplete(address: var_address, publicKey: var_publicKey);
  }

  @protected
  FfiDkgSession sse_decode_ffi_dkg_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    return FfiDkgSession(sessionId: var_sessionId);
  }

  @protected
  FfiGasEstimate sse_decode_ffi_gas_estimate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gasLimit = sse_decode_u_64(deserializer);
    var var_maxFeePerGas = sse_decode_String(deserializer);
    var var_maxPriorityFeePerGas = sse_decode_String(deserializer);
    var var_estimatedCostWei = sse_decode_String(deserializer);
    return FfiGasEstimate(
      gasLimit: var_gasLimit,
      maxFeePerGas: var_maxFeePerGas,
      maxPriorityFeePerGas: var_maxPriorityFeePerGas,
      estimatedCostWei: var_estimatedCostWei,
    );
  }

  @protected
  FfiKeyStatus sse_decode_ffi_key_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hasDeviceShard = sse_decode_bool(deserializer);
    var var_hasServerShard = sse_decode_bool(deserializer);
    var var_hasBackupShard = sse_decode_bool(deserializer);
    var var_address = sse_decode_String(deserializer);
    return FfiKeyStatus(
      hasDeviceShard: var_hasDeviceShard,
      hasServerShard: var_hasServerShard,
      hasBackupShard: var_hasBackupShard,
      address: var_address,
    );
  }

  @protected
  FfiPresignComplete sse_decode_ffi_presign_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_presigData = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiPresignComplete(presigData: var_presigData);
  }

  @protected
  FfiPresignRound1 sse_decode_ffi_presign_round_1(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiPresignRound1(sessionId: var_sessionId, payload: var_payload);
  }

  @protected
  FfiReshareComplete sse_decode_ffi_reshare_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiReshareComplete(address: var_address, publicKey: var_publicKey);
  }

  @protected
  FfiReshareRound1Result sse_decode_ffi_reshare_round_1_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messagesJson = sse_decode_list_String(deserializer);
    return FfiReshareRound1Result(messagesJson: var_messagesJson);
  }

  @protected
  FfiReshareSession sse_decode_ffi_reshare_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    return FfiReshareSession(sessionId: var_sessionId);
  }

  @protected
  FfiRound1Result sse_decode_ffi_round_1_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageJson = sse_decode_String(deserializer);
    return FfiRound1Result(messageJson: var_messageJson);
  }

  @protected
  FfiSignResult sse_decode_ffi_sign_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiSignResult(signature: var_signature);
  }

  @protected
  FfiSignRound1 sse_decode_ffi_sign_round_1(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_msgHash = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiSignRound1(
      sessionId: var_sessionId,
      payload: var_payload,
      msgHash: var_msgHash,
    );
  }

  @protected
  FfiTxResult sse_decode_ffi_tx_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txHash = sse_decode_String(deserializer);
    return FfiTxResult(txHash: var_txHash);
  }

  @protected
  FfiWalletInfo sse_decode_ffi_wallet_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiWalletInfo(address: var_address, publicKey: var_publicKey);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_ffi_balance(FfiBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.wei, serializer);
    sse_encode_String(self.formatted, serializer);
    sse_encode_u_8(self.decimals, serializer);
  }

  @protected
  void sse_encode_ffi_dkg_complete(
    FfiDkgComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_ffi_dkg_session(
    FfiDkgSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
  }

  @protected
  void sse_encode_ffi_gas_estimate(
    FfiGasEstimate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.gasLimit, serializer);
    sse_encode_String(self.maxFeePerGas, serializer);
    sse_encode_String(self.maxPriorityFeePerGas, serializer);
    sse_encode_String(self.estimatedCostWei, serializer);
  }

  @protected
  void sse_encode_ffi_key_status(FfiKeyStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hasDeviceShard, serializer);
    sse_encode_bool(self.hasServerShard, serializer);
    sse_encode_bool(self.hasBackupShard, serializer);
    sse_encode_String(self.address, serializer);
  }

  @protected
  void sse_encode_ffi_presign_complete(
    FfiPresignComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.presigData, serializer);
  }

  @protected
  void sse_encode_ffi_presign_round_1(
    FfiPresignRound1 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_ffi_reshare_complete(
    FfiReshareComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_ffi_reshare_round_1_result(
    FfiReshareRound1Result self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.messagesJson, serializer);
  }

  @protected
  void sse_encode_ffi_reshare_session(
    FfiReshareSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
  }

  @protected
  void sse_encode_ffi_round_1_result(
    FfiRound1Result self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.messageJson, serializer);
  }

  @protected
  void sse_encode_ffi_sign_result(
    FfiSignResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
  }

  @protected
  void sse_encode_ffi_sign_round_1(
    FfiSignRound1 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_list_prim_u_8_strict(self.msgHash, serializer);
  }

  @protected
  void sse_encode_ffi_tx_result(FfiTxResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txHash, serializer);
  }

  @protected
  void sse_encode_ffi_wallet_info(
    FfiWalletInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
